name: MinedStats
version: '${version}'
main: me.levitate.minedstats.MinedStats
api-version: '1.20'
authors: [Levitate]
description: A simple plugin to track broken blocks.
website: xlevitate.co
depend: [PlaceholderAPI]